### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Shiftenas**
I've made that the miss texts can be changed. 

noattackmisstext is the one that is displayed when the player don't press Z when attacking

defensemisstext is displayed when the enemy has too much defense

### CODE REVIEW

**Comment by RhenaudTheLukark** [comment]
Woah there, please remove all .meta files from the Default and Mods directories first then we can talk

**Comment by Shiftenas** [comment]
I don't find any

**Comment by Shiftenas** [comment]
Wait nvm

**Comment by RhenaudTheLukark** [comment]
Files changed: 236...
Most of them are .meta files from these two folders.

**Pull request closed without merging**
