### PR TITLE
make disclaimer menu nicer

### PR DESCRIPTION
**Pull request by scoobydoofacethingdie**
eh the bottom left 2 text's doesnt really look great in that position

### CODE REVIEW

**Comment by scoobydoofacethingdie** [comment]
forgot to put a image of what it looks like
here
new menu

**Comment by RhenaudTheLukark** [comment]
Hey man, sorry to say it, but as soon as you dropped that new version, all the active users thought that this new version of the Disclaimer screen you cooked up isn't nicer than the current one!

This is also my own opinion, as you see, you removed some crucial information from the Disclaimer screen (you only need Lua experience to __**make mods in CYF**__, not to __**use CYF**__), and removing the central alignment of the bottom text is not a good idea either.

If you want to revise the Disclaimer screen further, it's up to you, but I think it's pretty unanimous on our side that the current version of the Disclaimer screen is good enough as it is.

**Comment by scoobydoofacethingdie** [comment]
oh ok

**Comment by scoobydoofacethingdie** [comment]
oh ok

**Pull request closed without merging**
